### PR TITLE
Differentiate platforms by a different json name

### PR DESCRIPTION
**Pull request by juraj-blahunka**
Hi Building24, I'd like to start the conversation about differentiating JSON names of carthage specs. Carthage .version files don't properly handle current setup. If I add multiple platforms of Fabric "binary" dependency in my Cartfile, the generated `Carthage/Build/.Fabric.version` file gets overwritten and lists only one of the platforms. See https://github.com/Carthage/Carthage/issues/2430 for more details.
I found out, that it's possible to trick carthage into treating each "binary" dependency as unique, so that each entry generates its own .Fabric-Platform.version file.
Please LMK if this is something you could merge upstream.
Thanks!

### CODE REVIEW

**Comment by yvbeek** [comment]
I can see the benefit, but I'm a bit worried that this will break specs currently used by people.

**Comment by juraj-blahunka** [comment]
Gotcha, in the meantime, work has been done in Carthage, so that Carthage correctly processes archives with all platforms. I think it should be ready in 0.30.0 - https://github.com/Carthage/Carthage/issues/2430

**Comment by juraj-blahunka** [comment]
@Zyphrax With Carthage/Carthage#2430 it's now possible to use a single URL with a zip for all platforms. Instead of updating each .json file, there only needs to be a single .json, e.g.:

```
{
  "1.9.0": "https://kit-downloads.fabric.io/cocoapods/fabric/1.9.0/fabric.zip"
}
```

would you be willing to accept a PR where we'd drop all platform specific jsons in favor of a single json?

**Comment by yvbeek** [comment]
@juraj-blahunka That's great, makes it a bit easier to manage. I do want to make sure that we don't break existing configurations for now.

Maybe we should store the new JSON in a `Universal` folder?
For example `https://building42.github.io/Specs/Carthage/Universal/Fabric.json`

**Comment by juraj-blahunka** [comment]
@Zyphrax  Sounds great, I'll open a new PR with the Universal folder.

**Pull request closed without merging**
